#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 120
# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="dunst mpd picom unclutter pipewire remapd"
# DPI Scale
export GDK_DPI_SCALE=1.28
export QT_SCALE_FACTOR=1.28
export PASSWORD_STORE_CLIP_TIME=15
# Fan Boost
# /home/naimish/tuf-fan-boost-notification/FanNotifications.sh &
# GUI Polkit
/usr/bin/lxpolkit &
for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
